abbreviations = [
    'Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.', 'Sr.', 'Jr.', 'St.', 'Lt.', 'Capt.', 'Cpt.', 'Sgt.', 'Gen.', 
    'Gov.', 'Atty.', 'Supt.', 'Det.', 'Rev.', 'Hon.', 'Pres.', 'VP.', 'Sec.', 'Treas.', 'Pvt.', 'Cpl.', 
    'Maj.', 'Col.', 'Gen.', 'Adm.', 'Sen.', 'Rep.', 'Amb.', 'Treas.', 'Sec.', 'Pvt.', 'Ens.', 'Sgt.', 
    'Adm.', 'Mstr.', 'J.D.', 'M.D.', 'B.A.', 'M.A.', 'D.D.S.', 'Ph.D.', 'Esq.', 'Ltd.', 'Co.', 'Inc.', 
    'Corp.', 'Pty.', 'LLC.', 'L.P.', 'B.V.', 'S.A.', 'N.V.', 'GmbH.', 'M.B.A.', 'B.Sc.', 'M.Sc.', 'C.F.O.', 
    'C.E.O.', 'C.O.O.', 'C.T.O.', 'C.I.O.', 'C.M.O.', 'C.P.A.', 'A.B.', 'B.F.A.', 'M.F.A.', 'D.O.', 
    'B.C.', 'A.D.', 'a.m.', 'p.m.', 'et al.', 'etc.', 'e.g.', 'i.e.', 'cf.', 'vs.', 'sq.', 'ft.', 'lb.', 
    'oz.', 'gal.', 'ml.', 'l.', 'km.', 'm.', 'cm.', 'mm.', 'in.', 'ft.', 'yd.', 'mi.', 'Jan.', 'Feb.', 
    'Mar.', 'Apr.', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.', 'Mon.', 'Tue.', 'Wed.', 
    'Thu.', 'Fri.', 'Sat.', 'Sun.', 'U.S.', 'E.U.', 'U.K.', 'U.N.', 'N.A.T.O.', 'F.B.I.', 'C.I.A.', 
    'N.S.A.', 'I.R.S.', 'F.D.A.', 'C.D.C.', 'W.H.O.', 'N.A.S.A.', 'E.P.A.', 'G.D.P.', 'U.S.D.A.', 
    'dept.', 'div.', 'est.', 'min.', 'max.', 'approx.', 'ult.', 'prox.', 'temp.', 'vol.', 'no.', 'ex.', 
    'bk.', 'ch.', 'pg.', 'r.', 'v.', 'cv.', 'app.', 'ed.', 'trans.', 're.', 'lit.', 'lib.', 'mus.', 'arch.', 
    'phil.', 'math.', 'bio.', 'chem.', 'phys.', 'eco.', 'psy.', 'soc.', 'anth.', 'hist.', 'geo.', 'pol.', 
    'rel.', 'edu.', 'mil.', 'ind.', 'tech.', 'med.', 'leg.', 'art.', 'pop.', 'dec.', 'inst.', 'sym.', 
    'org.', 'dept.', 'univ.', 'assoc.', 'fed.', 'nat.', 'intl.', 'comp.', 'conf.', 'exh.', 'semin.', 
    'worksh.', 'pub.', 'doc.', 'ref.', 'vol.', 'iss.', 'edit.', 'rev.', 'comm.', 'abbr.', 'acron.', 
    'syn.', 'ant.', 'analog.', 'dict.', 'encyc.', 'man.', 'spec.', 'oper.', 'proc.', 'strat.', 'anal.', 
    'assess.', 'eval.', 'dev.', 'des.', 'impl.', 'maint.', 'admin.', 'mon.', 'sch.', 'acad.', 'sci.', 
    'eng.', 'res.', 'proj.', 'prog.', 'stud.', 'sess.', 'chap.', 'sect.', 'part.', 'line.', 'para.', 
    'pass.', 'vers.', 'examp.', 'quot.', 'comm.', 'note.', 'obser.', 'concl.', 'summ.', 'rec.', 'recom.', 
    'pref.', 'intro.', 'forew.', 'acknow.', 'bibl.', 'gloss.', 'indx.', 'appx.', 'annex.', 'suppl.', 
    'addend.', 'corr.', 'postscr.', 'pseud.', 'init.', 'signat.', 'inscr.', 'marg.', 'footn.', 'endn.', 
    'bibliog.', 'biog.', 'autob' ]
